import type { Locale } from "./i18n";

const baseKeys = ["overview","repositories","tasks","activity","installations","workspace","navigation","openMenu","closeMenu","overviewLead","repositoriesLead","tasksLead","activityLead","search","filter","all","active","paused","on","off","admin","readOnly","updated","openSettings","page","previous","next","scoped","scope","partial","window","jobs","pending","running","failed","done","recentTasks","viewAll","repositoryStatus","noActivity","noResults","processingHint","settings","settingsHint","saveHint","backfillHelp","cleanupHelp","allRetained","due","stale","preview","previewLead","previewDisclosure","previewTitle","previewBody","previewKind","issue","pullRequest","runPreview","previewOnly","previewCandidates","previewNoMatch","previewSelected","previewThreshold","previewInvalid","previewNoCandidates","previewNotConfigured","previewRateLimited","previewUnavailable","cleanupTasks","scanned","nextRepoPage","historyLimit","cleanupLimit"] as const;
const globalKeys = ["allAccounts","globalLead","globalCoverage","globalPartial","accounts","accountsLead","writableRepositories","visibleRepositories","workQueue","accountDashboard","accountPage","coverageLimited"] as const;
const interactionKeys = ["switchAccount", "currentAccount", "manageInstallations", "clearSearch", "submitting", "submittedHint", "accountScope", "unsavedChanges"] as const;
const aiKeys = ["aiService","aiLead","aiMode","aiPlatform","aiByok","aiProtocol","aiOpenAI","aiJev","aiBaseUrl","aiModel","aiKey","aiKeySaved","aiKeyMissing","aiKeyHint","aiSave","aiTest","aiTestHint","aiRemove","aiRemoveConfirm","aiRemoved","aiSaved","aiTested","aiInvalid","aiKeyRequired","aiStorageUnavailable","aiUnavailable","aiRateLimited","aiPrivacy","aiCapabilities","aiNoFallback","aiReady","aiNotReady","aiPlatformHint","aiShowKey","aiHideKey"] as const;
const keys = [...baseKeys, ...interactionKeys, ...globalKeys, ...aiKeys, "aiGreetingsUnavailable", "aiModelHint", "aiSavedConfiguration"] as const;
export type AdminMessages = Record<typeof keys[number], string>;
const interactionCatalogs: Record<Locale,string> = {
 en: "Switch account|Current account|Manage installations|Clear search|Submitting…|Waiting for the server. Please keep this page open.|GitHub account|You have unsaved settings. Leave this page and discard your changes?",
 zh: "切换账户|当前账户|管理安装|清除搜索|提交中…|正在等待服务器响应，请保持页面打开。|GitHub 账户|设置尚未保存。确定离开并放弃更改吗？",
 ja: "アカウントを切り替え|現在のアカウント|インストールを管理|検索をクリア|送信中…|サーバーの応答を待っています。このページを開いたままにしてください。|GitHub アカウント|未保存の設定があります。変更を破棄してこのページを離れますか？",
 ko: "계정 전환|현재 계정|설치 관리|검색 지우기|제출 중…|서버 응답을 기다리는 중입니다. 이 페이지를 열어 두세요.|GitHub 계정|저장하지 않은 설정이 있습니다. 변경 사항을 버리고 이 페이지를 떠날까요?",
 es: "Cambiar cuenta|Cuenta actual|Gestionar instalaciones|Borrar búsqueda|Enviando…|Esperando al servidor. Mantén esta página abierta.|Cuenta de GitHub|Hay ajustes sin guardar. ¿Quieres salir y descartar los cambios?",
 pt: "Trocar conta|Conta atual|Gerenciar instalações|Limpar busca|Enviando…|Aguardando o servidor. Mantenha esta página aberta.|Conta do GitHub|Há configurações não salvas. Deseja sair e descartar as alterações?",
 id: "Ganti akun|Akun saat ini|Kelola instalasi|Hapus pencarian|Mengirim…|Menunggu server. Biarkan halaman ini tetap terbuka.|Akun GitHub|Ada pengaturan yang belum disimpan. Tinggalkan halaman dan batalkan perubahan?",
 vi: "Chuyển tài khoản|Tài khoản hiện tại|Quản lý bản cài đặt|Xóa tìm kiếm|Đang gửi…|Đang chờ máy chủ. Hãy giữ trang này mở.|Tài khoản GitHub|Có cài đặt chưa lưu. Rời trang và bỏ các thay đổi?",
 ar: "تبديل الحساب|الحساب الحالي|إدارة عمليات التثبيت|مسح البحث|جارٍ الإرسال…|بانتظار الخادم. يرجى إبقاء هذه الصفحة مفتوحة.|حساب GitHub|لديك إعدادات غير محفوظة. هل تريد مغادرة الصفحة وتجاهل التغييرات؟",
};
// Every dashboard string has a complete catalog, following the site's nine locales.
const catalogs: Record<Locale,string> = {
 en: `Dashboard|Repositories|Tasks|Activity|Installations|Workspace|Navigation|Open navigation|Close navigation|A clear view of your bot's work, repository settings, and recent changes.|Manage processing and optional features for repositories you can write to.|Inspect retained jobs, filter their status, and safely retry failures.|Repository settings and operations, with who changed them and when.|Search repositories or task ID|Apply filters|All|Active|Paused|On|Off|Administrator|Read only|Last updated|Open settings|Page|Previous|Next|Scoped view|{authorized} writable repositories from {checked} checked; {total} accessible in this installation.|This is one repository page. Counters do not cover the whole installation.|Jobs updated in the last 30 days|Retained jobs|Pending|Running|Failed|Completed|Issue / PR processing|View all|Repository status|No recorded activity|No matching results|Processing changes apply to future events. Historical scans start only when requested.|Settings|Choose processing behavior and optional features for this repository.|Changes take effect after you save.|Backfill processes a bounded batch of existing issues and pull requests. It never starts automatically.|Preview exactly what the bot can remove, then confirm the saved plan. GitHub changes begin only after confirmation.|All retained history · current repository page|Due now|Expired leases|Intent preview|Test a synthetic issue or pull request against the saved allowed labels.|Your sample is sent to the configured classification provider. Use synthetic text; do not paste secrets. The sample is not saved.|Title|Body (optional)|Sample type|Issue|Pull request|Run preview|Preview only: no GitHub changes or historical scan.|Saved label candidates|No saved label passed the classifier threshold.|Selected labels|Minimum probability|Enter a title of 1–256 characters and a body of at most 8,000 characters.|Save at least one existing allowed label in Settings before previewing.|The intent classifier is not configured.|Too many previews. Try again in a minute.|The classifier is unavailable. Try again later.|Cleanup tasks|{done} completed · {skipped} skipped · {total} planned|Change repository page|History page limit reached.|The newest 25 cleanup tasks in this repository scope are shown.`,
 zh: `控制台|仓库|任务|动态|安装|工作空间|导航|打开导航|关闭导航|查看机器人任务、仓库设置和最近变更。|管理你有写入权限的仓库的处理行为与可选功能。|查看保留的任务、按状态筛选并安全重试失败任务。|查看仓库设置与操作记录，以及操作者和时间。|搜索仓库或任务 ID|应用筛选|全部|运行中|已暂停|开启|关闭|管理员|只读|最近更新|打开设置|页|上一页|下一页|限定范围|本页检查 {checked} 个仓库，其中 {authorized} 个有写入权限；本次安装共可访问 {total} 个仓库。|当前仅为一个仓库分页，统计不代表整个安装。|最近 30 天更新的任务|保留任务|待处理|执行中|失败|已完成|Issue / PR 处理|查看全部|仓库状态|暂无记录|没有匹配结果|处理设置仅影响后续事件。历史扫描只会在手动请求后开始。|设置|设置本仓库的处理行为与可选功能。|保存后更改才会生效。|补处理仅扫描指定数量的历史 Issue 和 Pull Request，不会自动开始。|先预览机器人可移除的内容，再确认已保存的计划。确认前不会修改 GitHub。|所有保留记录 · 当前仓库分页|现可执行|租约已过期|意图预览|用虚构的 Issue 或 Pull Request 测试已保存的允许标签。|示例文本会发送到已配置的分类服务。请使用虚构内容，不要粘贴密钥。示例不会保存。|标题|正文（可选）|示例类型|Issue|Pull Request|运行预览|仅预览：不修改 GitHub，也不扫描历史内容。|已保存的候选标签|没有已保存的标签达到分类阈值。|选中标签|最低概率|标题需为 1–256 个字符，正文最多 8,000 个字符。|预览前请在设置中保存至少一个现有的允许标签。|尚未配置意图分类服务。|预览次数过多，请稍等一分钟再试。|分类服务暂不可用，请稍后重试。|清理任务|已完成 {done} · 已跳过 {skipped} · 计划 {total}|切换仓库分页|已达到历史记录分页上限。|显示当前仓库范围内最近的 25 个清理任务。`,
 ja: `ダッシュボード|リポジトリ|タスク|履歴|インストール|ワークスペース|ナビゲーション|ナビゲーションを開く|ナビゲーションを閉じる|ボットの処理、リポジトリ設定、最近の変更を確認します。|書き込み権限のあるリポジトリの処理と任意機能を管理します。|保存されたジョブを確認し、状態で絞り込み、失敗を安全に再試行します。|設定と操作の変更者および時刻を確認します。|リポジトリまたはタスク ID を検索|絞り込む|すべて|有効|停止中|オン|オフ|管理者|読み取り専用|最終更新|設定を開く|ページ|前へ|次へ|対象範囲|確認した {checked} 件中、書き込み可能なリポジトリは {authorized} 件。インストールでアクセス可能な件数は {total} 件です。|リポジトリの1ページ分です。集計はインストール全体を対象としません。|過去30日間に更新されたジョブ|保存されたジョブ|待機中|実行中|失敗|完了|Issue / PR の処理|すべて表示|リポジトリの状態|記録された履歴はありません|一致する結果はありません|処理設定は今後のイベントに適用されます。履歴スキャンは手動で開始します。|設定|このリポジトリの処理と任意機能を選択します。|保存すると変更が反映されます。|バックフィルは指定件数の既存 Issue と Pull Request を処理します。自動では開始しません。|削除対象をプレビューし、保存された計画を確認します。確認後にのみ GitHub が変更されます。|保存された全履歴 · 現在のリポジトリページ|実行可能|期限切れリース|意図のプレビュー|架空の Issue や Pull Request で保存済みの許可ラベルをテストします。|サンプルは設定された分類サービスに送信されます。架空の文章を使い、機密情報を貼り付けないでください。サンプルは保存されません。|タイトル|本文（任意）|サンプルの種類|Issue|Pull Request|プレビューを実行|プレビューのみ：GitHub の変更や履歴スキャンは行いません。|保存済みの候補ラベル|分類しきい値を満たす保存済みラベルはありません。|選択されたラベル|最低確率|タイトルは1～256文字、本文は最大8,000文字で入力してください。|設定で既存の許可ラベルを1つ以上保存してください。|意図分類サービスが設定されていません。|プレビューが多すぎます。1分後に再試行してください。|分類サービスを利用できません。後で再試行してください。|クリーンアップタスク|完了 {done} · スキップ {skipped} · 計画 {total}|リポジトリページを変更|履歴ページの上限に達しました。|対象リポジトリ内の最新25件のクリーンアップタスクを表示しています。`,
 ko: `대시보드|저장소|작업|활동|설치|작업 공간|탐색|탐색 열기|탐색 닫기|봇 작업, 저장소 설정과 최근 변경 사항을 확인하세요.|쓰기 권한이 있는 저장소의 처리와 선택 기능을 관리하세요.|보관된 작업을 상태별로 필터링하고 실패한 작업을 안전하게 재시도하세요.|저장소 설정과 작업의 변경자 및 시간을 확인하세요.|저장소 또는 작업 ID 검색|필터 적용|전체|활성|일시 중지|켜짐|꺼짐|관리자|읽기 전용|최근 업데이트|설정 열기|페이지|이전|다음|범위 제한 보기|확인한 {checked}개 중 쓰기 가능한 저장소 {authorized}개. 이 설치에서 접근 가능한 저장소는 {total}개입니다.|현재 저장소 한 페이지의 통계이며 전체 설치를 포함하지 않습니다.|최근 30일 동안 업데이트된 작업|보관된 작업|대기|실행 중|실패|완료|Issue / PR 처리|전체 보기|저장소 상태|기록된 활동 없음|일치하는 결과 없음|처리 변경은 이후 이벤트에 적용됩니다. 기록 스캔은 요청할 때만 시작됩니다.|설정|이 저장소의 처리 동작과 선택 기능을 설정하세요.|저장한 후 변경 사항이 적용됩니다.|일괄 처리는 지정된 수의 기존 Issue와 Pull Request만 처리하며 자동으로 시작하지 않습니다.|봇이 삭제할 수 있는 항목을 미리 보고 저장된 계획을 확인하세요. 확인 후에만 GitHub를 변경합니다.|보관된 전체 기록 · 현재 저장소 페이지|지금 실행 가능|만료된 임대|의도 미리보기|가상 Issue나 Pull Request로 저장된 허용 라벨을 테스트하세요.|샘플이 설정된 분류 제공업체로 전송됩니다. 가상 텍스트를 사용하고 비밀을 붙여 넣지 마세요. 샘플은 저장하지 않습니다.|제목|본문 (선택)|샘플 유형|Issue|Pull Request|미리보기 실행|미리보기만 수행: GitHub 변경이나 기록 스캔 없음.|저장된 후보 라벨|분류 임계값을 넘은 저장 라벨이 없습니다.|선택한 라벨|최소 확률|제목은 1–256자, 본문은 최대 8,000자로 입력하세요.|설정에서 기존 허용 라벨을 하나 이상 저장하세요.|의도 분류기가 설정되지 않았습니다.|미리보기가 너무 많습니다. 1분 후 다시 시도하세요.|분류기를 사용할 수 없습니다. 나중에 다시 시도하세요.|정리 작업|완료 {done} · 건너뜀 {skipped} · 계획 {total}|저장소 페이지 변경|기록 페이지 한도에 도달했습니다.|현재 저장소 범위의 최근 정리 작업 25개를 표시합니다.`,
 es: `Panel de control|Repositorios|Tareas|Actividad|Instalaciones|Espacio de trabajo|Navegación|Abrir navegación|Cerrar navegación|Consulta el trabajo del bot, la configuración y los cambios recientes.|Gestiona el procesamiento y las funciones opcionales de los repositorios donde puedes escribir.|Consulta los trabajos guardados, filtra su estado y reintenta fallos de forma segura.|Configuración y operaciones del repositorio, con autor y fecha.|Buscar repositorio o ID de tarea|Aplicar filtros|Todos|Activo|Pausado|Sí|No|Administrador|Solo lectura|Última actualización|Abrir configuración|Página|Anterior|Siguiente|Vista limitada|{authorized} repositorios con escritura de {checked} comprobados; {total} accesibles en esta instalación.|Esta es una página de repositorios. Los contadores no cubren toda la instalación.|Trabajos actualizados en los últimos 30 días|Trabajos guardados|Pendiente|En ejecución|Fallidos|Completados|Procesamiento de issues / PR|Ver todo|Estado del repositorio|Sin actividad registrada|No hay coincidencias|Los cambios se aplican a eventos futuros. Los análisis históricos comienzan solo bajo petición.|Configuración|Elige el procesamiento y las funciones opcionales del repositorio.|Los cambios se aplican al guardar.|La carga histórica procesa un lote limitado de issues y pull requests. No se inicia automáticamente.|Revisa lo que puede eliminar el bot y confirma el plan guardado. GitHub cambia solo después de la confirmación.|Todo el historial guardado · página actual de repositorios|Listos ahora|Arrendamientos vencidos|Vista previa de intención|Prueba un issue o pull request ficticio con las etiquetas permitidas guardadas.|La muestra se envía al proveedor de clasificación configurado. Usa texto ficticio y no pegues secretos. No se guarda la muestra.|Título|Contenido (opcional)|Tipo de muestra|Issue|Pull request|Ejecutar vista previa|Solo vista previa: sin cambios en GitHub ni análisis histórico.|Etiquetas candidatas guardadas|Ninguna etiqueta guardada superó el umbral del clasificador.|Etiquetas seleccionadas|Probabilidad mínima|Introduce un título de 1–256 caracteres y hasta 8.000 caracteres de contenido.|Guarda al menos una etiqueta permitida existente en Configuración.|El clasificador de intención no está configurado.|Demasiadas vistas previas. Inténtalo en un minuto.|El clasificador no está disponible. Inténtalo más tarde.|Tareas de limpieza|{done} completados · {skipped} omitidos · {total} previstos|Cambiar página de repositorios|Se alcanzó el límite de páginas del historial.|Se muestran las 25 tareas de limpieza más recientes en este grupo de repositorios.`,
 pt: `Painel|Repositórios|Tarefas|Atividade|Instalações|Espaço de trabalho|Navegação|Abrir navegação|Fechar navegação|Acompanhe o trabalho do bot, as configurações e as alterações recentes.|Gerencie o processamento e os recursos opcionais dos repositórios com acesso de escrita.|Veja os trabalhos guardados, filtre por status e repita falhas com segurança.|Configurações e operações do repositório, com autor e horário.|Pesquisar repositório ou ID da tarefa|Aplicar filtros|Todos|Ativo|Pausado|Ligado|Desligado|Administrador|Somente leitura|Última atualização|Abrir configurações|Página|Anterior|Próxima|Visão limitada|{authorized} repositórios com escrita entre {checked} verificados; {total} acessíveis nesta instalação.|Esta é uma página de repositórios. Os contadores não abrangem toda a instalação.|Trabalhos atualizados nos últimos 30 dias|Trabalhos guardados|Pendente|Em execução|Falhas|Concluídos|Processamento de issues / PR|Ver todos|Status dos repositórios|Sem atividade registrada|Nenhum resultado correspondente|As mudanças se aplicam a eventos futuros. A análise histórica começa apenas quando solicitada.|Configurações|Escolha o processamento e os recursos opcionais deste repositório.|As alterações passam a valer após salvar.|O preenchimento histórico processa um lote limitado de issues e pull requests. Não começa automaticamente.|Veja o que o bot pode remover e confirme o plano salvo. O GitHub só muda após a confirmação.|Todo o histórico guardado · página atual de repositórios|Prontos agora|Concessões expiradas|Prévia de intenção|Teste uma issue ou pull request fictícia com os rótulos permitidos salvos.|A amostra é enviada ao provedor de classificação configurado. Use texto fictício e não cole segredos. A amostra não é salva.|Título|Conteúdo (opcional)|Tipo de amostra|Issue|Pull request|Executar prévia|Somente prévia: sem alterações no GitHub ou análise histórica.|Rótulos candidatos salvos|Nenhum rótulo salvo atingiu o limite do classificador.|Rótulos selecionados|Probabilidade mínima|Insira um título de 1–256 caracteres e conteúdo de até 8.000 caracteres.|Salve pelo menos um rótulo permitido existente em Configurações.|O classificador de intenção não está configurado.|Muitas prévias. Tente novamente em um minuto.|O classificador está indisponível. Tente mais tarde.|Tarefas de limpeza|{done} concluídos · {skipped} ignorados · {total} planejados|Mudar página de repositórios|Limite de páginas do histórico atingido.|São exibidas as 25 tarefas de limpeza mais recentes neste grupo de repositórios.`,
 id: `Dasbor|Repositori|Tugas|Aktivitas|Instalasi|Ruang kerja|Navigasi|Buka navigasi|Tutup navigasi|Lihat pekerjaan bot, pengaturan repositori, dan perubahan terbaru.|Kelola pemrosesan dan fitur opsional repositori yang dapat Anda tulis.|Lihat pekerjaan tersimpan, filter statusnya, dan coba ulang kegagalan dengan aman.|Pengaturan dan operasi repositori beserta pelaku dan waktunya.|Cari repositori atau ID tugas|Terapkan filter|Semua|Aktif|Dijeda|Aktif|Nonaktif|Administrator|Hanya baca|Terakhir diperbarui|Buka pengaturan|Halaman|Sebelumnya|Berikutnya|Tampilan terbatas|{authorized} repositori dapat ditulis dari {checked} yang diperiksa; {total} dapat diakses dalam instalasi ini.|Ini satu halaman repositori. Penghitung tidak mencakup seluruh instalasi.|Pekerjaan diperbarui dalam 30 hari terakhir|Pekerjaan tersimpan|Menunggu|Berjalan|Gagal|Selesai|Pemrosesan Issue / PR|Lihat semua|Status repositori|Belum ada aktivitas tercatat|Tidak ada hasil yang cocok|Perubahan berlaku untuk peristiwa berikutnya. Pemindaian riwayat hanya dimulai saat diminta.|Pengaturan|Pilih perilaku pemrosesan dan fitur opsional repositori ini.|Perubahan berlaku setelah disimpan.|Pemrosesan riwayat mencakup sejumlah issue dan pull request yang dibatasi. Tidak dimulai otomatis.|Pratinjau item yang dapat dihapus bot, lalu konfirmasi rencana tersimpan. GitHub berubah hanya setelah konfirmasi.|Semua riwayat tersimpan · halaman repositori saat ini|Siap sekarang|Sewa kedaluwarsa|Pratinjau maksud|Uji issue atau pull request buatan dengan label yang diizinkan dan tersimpan.|Sampel dikirim ke penyedia klasifikasi yang dikonfigurasi. Gunakan teks buatan tanpa rahasia. Sampel tidak disimpan.|Judul|Isi (opsional)|Jenis sampel|Issue|Pull request|Jalankan pratinjau|Hanya pratinjau: tanpa perubahan GitHub atau pemindaian riwayat.|Kandidat label tersimpan|Tidak ada label tersimpan yang melampaui ambang klasifikasi.|Label terpilih|Probabilitas minimum|Masukkan judul 1–256 karakter dan isi maksimal 8.000 karakter.|Simpan setidaknya satu label diizinkan yang ada di Pengaturan.|Pengklasifikasi maksud belum dikonfigurasi.|Terlalu banyak pratinjau. Coba lagi dalam satu menit.|Pengklasifikasi tidak tersedia. Coba lagi nanti.|Tugas pembersihan|{done} selesai · {skipped} dilewati · {total} direncanakan|Ganti halaman repositori|Batas halaman riwayat tercapai.|Menampilkan 25 tugas pembersihan terbaru dalam lingkup repositori ini.`,
 vi: `Bảng điều khiển|Kho mã|Tác vụ|Hoạt động|Bản cài đặt|Không gian làm việc|Điều hướng|Mở điều hướng|Đóng điều hướng|Xem công việc của bot, cài đặt kho mã và các thay đổi gần đây.|Quản lý xử lý và các tính năng tùy chọn cho kho mã có quyền ghi.|Xem tác vụ lưu trữ, lọc trạng thái và thử lại an toàn các lỗi.|Cài đặt và thao tác của kho mã cùng người thực hiện và thời gian.|Tìm kho mã hoặc ID tác vụ|Áp dụng bộ lọc|Tất cả|Hoạt động|Tạm dừng|Bật|Tắt|Quản trị viên|Chỉ đọc|Cập nhật gần nhất|Mở cài đặt|Trang|Trước|Tiếp|Phạm vi giới hạn|{authorized} kho mã có quyền ghi trong {checked} kho đã kiểm tra; {total} kho có thể truy cập trong bản cài đặt.|Đây là một trang kho mã. Số liệu không bao gồm toàn bộ bản cài đặt.|Tác vụ cập nhật trong 30 ngày qua|Tác vụ lưu trữ|Chờ xử lý|Đang chạy|Thất bại|Hoàn thành|Xử lý Issue / PR|Xem tất cả|Trạng thái kho mã|Chưa có hoạt động được ghi lại|Không có kết quả phù hợp|Thay đổi áp dụng cho sự kiện tiếp theo. Quét lịch sử chỉ bắt đầu khi được yêu cầu.|Cài đặt|Chọn cách xử lý và tính năng tùy chọn cho kho mã này.|Thay đổi có hiệu lực sau khi lưu.|Xử lý lịch sử quét một số lượng issue và pull request giới hạn. Không tự động bắt đầu.|Xem trước những gì bot có thể xóa, rồi xác nhận kế hoạch đã lưu. GitHub chỉ thay đổi sau xác nhận.|Toàn bộ lịch sử lưu trữ · trang kho mã hiện tại|Có thể chạy ngay|Phiên thuê hết hạn|Xem trước ý định|Thử issue hoặc pull request giả lập với các nhãn được phép đã lưu.|Mẫu được gửi tới dịch vụ phân loại đã cấu hình. Dùng văn bản giả lập, không dán bí mật. Mẫu không được lưu.|Tiêu đề|Nội dung (tùy chọn)|Loại mẫu|Issue|Pull request|Chạy xem trước|Chỉ xem trước: không sửa GitHub hoặc quét lịch sử.|Nhãn ứng viên đã lưu|Không có nhãn đã lưu nào đạt ngưỡng phân loại.|Nhãn được chọn|Xác suất tối thiểu|Nhập tiêu đề 1–256 ký tự và nội dung tối đa 8.000 ký tự.|Lưu ít nhất một nhãn được phép hiện có trong Cài đặt.|Chưa cấu hình bộ phân loại ý định.|Quá nhiều lần xem trước. Hãy thử lại sau một phút.|Bộ phân loại không khả dụng. Hãy thử lại sau.|Tác vụ dọn dẹp|{done} hoàn tất · {skipped} bỏ qua · {total} dự kiến|Đổi trang kho mã|Đã đạt giới hạn trang lịch sử.|Hiển thị 25 tác vụ dọn dẹp mới nhất trong phạm vi kho mã này.`,
 ar: `لوحة التحكم|المستودعات|المهام|النشاط|عمليات التثبيت|مساحة العمل|التنقل|فتح التنقل|إغلاق التنقل|اطّلع على أعمال الروبوت وإعدادات المستودعات والتغييرات الأخيرة.|إدارة المعالجة والميزات الاختيارية للمستودعات التي تملك صلاحية الكتابة فيها.|عرض المهام المحفوظة وتصفية حالتها وإعادة محاولة المهام الفاشلة بأمان.|إعدادات المستودعات والعمليات مع اسم المنفّذ والوقت.|البحث عن مستودع أو معرّف مهمة|تطبيق المرشحات|الكل|نشط|متوقف مؤقتًا|مفعّل|معطّل|مسؤول|للقراءة فقط|آخر تحديث|فتح الإعدادات|الصفحة|السابق|التالي|عرض محدد النطاق|{authorized} مستودعات قابلة للكتابة من أصل {checked} تم فحصها؛ {total} مستودعات متاحة في هذا التثبيت.|هذه صفحة واحدة من المستودعات. لا تشمل العدادات التثبيت بأكمله.|المهام المحدّثة خلال آخر 30 يومًا|المهام المحفوظة|قيد الانتظار|قيد التنفيذ|فاشلة|مكتملة|معالجة المشكلات وطلبات السحب|عرض الكل|حالة المستودعات|لا يوجد نشاط مسجّل|لا توجد نتائج مطابقة|تطبّق التغييرات على الأحداث القادمة. يبدأ فحص السجل فقط عند طلبه.|الإعدادات|اختر سلوك المعالجة والميزات الاختيارية لهذا المستودع.|تسري التغييرات بعد الحفظ.|تعالج العملية دفعة محدودة من المشكلات وطلبات السحب الموجودة. لا تبدأ تلقائيًا.|اعرض ما يمكن للروبوت إزالته ثم أكّد الخطة المحفوظة. لا يتغيّر GitHub إلا بعد التأكيد.|كل السجل المحفوظ · صفحة المستودعات الحالية|جاهزة الآن|إيجارات منتهية|معاينة النية|اختبر مشكلة أو طلب سحب افتراضيًا باستخدام التسميات المسموح بها المحفوظة.|تُرسل العيّنة إلى مزوّد التصنيف المحدّد. استخدم نصًا افتراضيًا ولا تلصق أسرارًا. لا تُحفظ العيّنة.|العنوان|النص (اختياري)|نوع العيّنة|مشكلة|طلب سحب|تشغيل المعاينة|معاينة فقط: دون تغييرات في GitHub أو فحص للسجل.|التسميات المرشّحة المحفوظة|لم تبلغ أي تسمية محفوظة عتبة التصنيف.|التسميات المختارة|الاحتمال الأدنى|أدخل عنوانًا من 1 إلى 256 حرفًا ونصًا لا يتجاوز 8,000 حرف.|احفظ تسمية موجودة واحدة على الأقل ضمن التسميات المسموح بها في الإعدادات.|لم يتم إعداد مصنّف النية.|معاينات كثيرة جدًا. حاول مجددًا بعد دقيقة.|المصنّف غير متاح. حاول لاحقًا.|مهام التنظيف|{done} مكتملة · {skipped} متجاوزة · {total} مخططة|تغيير صفحة المستودعات|تم بلوغ الحد الأقصى لصفحات السجل.|تُعرض أحدث 25 مهمة تنظيف ضمن نطاق المستودعات الحالي.`,
};
const globalCatalogs: Record<Locale,string> = {
 en: "All accounts|Jobs, repository controls, and recent changes across your GitHub accounts.|{checked} of {total} accounts · {authorized} writable repositories from {checkedRepos} checked.|Coverage is limited to the accounts and repository page shown. Use paging to inspect the remaining scope.|Accounts|Live access and retained work within the account and repository scope shown.|Writable repositories|Repositories in view|Work queue|Open account dashboard|Account page|Limited coverage",
 zh: "所有账户|查看所有 GitHub 账户的任务、仓库控制与最近变更。|已检查 {checked}/{total} 个账户 · {checkedRepos} 个仓库中 {authorized} 个可写。|当前仅覆盖显示的账户与仓库分页。请翻页查看其余范围。|账户|当前账户与仓库范围内的实时权限和保留任务。|可写仓库|当前范围内仓库|待处理任务|打开账户控制台|账户分页|覆盖范围有限",
 ja: "すべてのアカウント|GitHub アカウント全体のジョブ、リポジトリ管理、最近の変更。|{total} アカウント中 {checked} 件を確認 · {checkedRepos} リポジトリ中 {authorized} 件に書き込み可能。|表示中のアカウントとリポジトリページに限定されています。残りはページを切り替えて確認してください。|アカウント|表示対象のアカウントとリポジトリの権限と保存されたジョブ。|書き込み可能なリポジトリ|表示中のリポジトリ|処理待ち|アカウントのダッシュボードを開く|アカウントページ|対象範囲が限定",
 ko: "모든 계정|GitHub 계정 전체의 작업, 저장소 관리 및 최근 변경 사항입니다.|{total}개 계정 중 {checked}개 확인 · {checkedRepos}개 저장소 중 {authorized}개 쓰기 가능.|표시된 계정 및 저장소 페이지 범위입니다. 나머지는 페이지를 변경해 확인하세요.|계정|표시된 계정 및 저장소 범위의 현재 권한과 보관 작업입니다.|쓰기 가능한 저장소|표시된 저장소|작업 대기열|계정 대시보드 열기|계정 페이지|제한된 범위",
 es: "Todas las cuentas|Trabajos, controles de repositorios y cambios recientes de tus cuentas de GitHub.|{checked} de {total} cuentas · {authorized} repositorios con escritura de {checkedRepos} comprobados.|La cobertura se limita a las cuentas y la página de repositorios mostradas. Usa la paginación para revisar el resto.|Cuentas|Acceso actual y trabajos retenidos en el ámbito de cuentas y repositorios mostrado.|Repositorios con escritura|Repositorios visibles|Cola de trabajo|Abrir panel de la cuenta|Página de cuentas|Cobertura limitada",
 pt: "Todas as contas|Tarefas, controles de repositórios e alterações recentes nas suas contas do GitHub.|{checked} de {total} contas · {authorized} repositórios com escrita entre {checkedRepos} verificados.|A cobertura se limita às contas e à página de repositórios exibidas. Use a paginação para ver o restante.|Contas|Acesso atual e tarefas mantidas no escopo de contas e repositórios exibido.|Repositórios com escrita|Repositórios em exibição|Fila de tarefas|Abrir painel da conta|Página de contas|Cobertura limitada",
 id: "Semua akun|Tugas, kontrol repositori, dan perubahan terbaru di seluruh akun GitHub Anda.|{checked} dari {total} akun · {authorized} repositori dapat ditulis dari {checkedRepos} diperiksa.|Cakupan terbatas pada akun dan halaman repositori yang ditampilkan. Gunakan halaman berikutnya untuk memeriksa sisanya.|Akun|Akses saat ini dan tugas tersimpan dalam cakupan akun dan repositori yang ditampilkan.|Repositori dapat ditulis|Repositori ditampilkan|Antrean tugas|Buka dasbor akun|Halaman akun|Cakupan terbatas",
 vi: "Tất cả tài khoản|Tác vụ, điều khiển kho mã và thay đổi gần đây trên các tài khoản GitHub.|Đã kiểm tra {checked}/{total} tài khoản · {authorized} kho mã có quyền ghi trong {checkedRepos} kho đã kiểm tra.|Phạm vi giới hạn ở các tài khoản và trang kho mã hiển thị. Chuyển trang để xem phần còn lại.|Tài khoản|Quyền hiện tại và tác vụ lưu trữ trong phạm vi tài khoản và kho mã hiển thị.|Kho mã có quyền ghi|Kho mã đang hiển thị|Hàng đợi tác vụ|Mở bảng điều khiển tài khoản|Trang tài khoản|Phạm vi hạn chế",
 ar: "جميع الحسابات|المهام وعناصر التحكم في المستودعات والتغييرات الأخيرة عبر حسابات GitHub.|تم فحص {checked} من {total} حسابات · {authorized} مستودعات قابلة للكتابة من {checkedRepos} تم فحصها.|تقتصر التغطية على الحسابات وصفحة المستودعات المعروضة. استخدم الصفحات لفحص النطاق المتبقي.|الحسابات|الصلاحيات الحالية والمهام المحفوظة ضمن نطاق الحسابات والمستودعات المعروض.|المستودعات القابلة للكتابة|المستودعات المعروضة|قائمة المهام|فتح لوحة تحكم الحساب|صفحة الحسابات|تغطية محدودة",
};
const aiCatalogs: Record<Locale,string> = {
 en: "AI service|Choose this repository’s AI service. Processing and allowed labels stay unchanged.|Service mode|Platform service|Your own provider (BYOK)|Protocol|OpenAI compatible|Jev classifier|Base URL|Model|API key|A key is saved; its value is hidden.|No key is saved.|Leave blank to keep the saved key. Changing the URL or protocol requires a new key.|Save service|Test connection|Tests the saved configuration with a small synthetic request. Save changes first. Your provider may charge for this test.|Delete key|I confirm deletion of this repository’s saved key.|The saved key was deleted.|AI service saved.|Connection test succeeded.|Check the protocol, HTTPS base URL, and model.|Enter a new API key when changing the URL or protocol.|Secure key storage is unavailable. Contact the platform administrator.|The saved AI service could not be reached or authenticated. Check its settings and try again.|Too many connection tests. Try again in a minute.|In BYOK mode, when enabled, issue or PR titles, bodies and label candidates are sent to your endpoint. Your provider bills you. This configuration applies only to this repository.|Jev supports label classification only. OpenAI compatible services can also generate AI greetings.|An unavailable BYOK service never falls back to the platform. Saving a service does not enable intent labeling or comments.|Ready|Not ready|Uses the platform’s configured AI service. Custom-provider fields apply only in BYOK mode.|Show key|Hide key",
 zh: "AI 服务|选择本仓库的 AI 服务，处理开关和允许标签保持不变。|服务模式|平台服务|自有服务（BYOK）|协议|OpenAI 兼容|Jev 分类器|基础 URL|模型|API 密钥|已保存密钥，其内容不会显示。|尚未保存密钥。|留空保留原密钥。更改 URL 或协议时必须输入新密钥。|保存服务|测试连接|用少量虚构内容测试已保存的配置，请先保存更改。服务商可能对此测试收费。|删除密钥|我确认删除本仓库已保存的密钥。|已删除保存的密钥。|已保存 AI 服务。|连接测试成功。|请检查协议、HTTPS 基础 URL 和模型。|更改 URL 或协议时请输入新 API 密钥。|安全密钥存储不可用，请联系平台管理员。|无法连接或验证已保存的 AI 服务，请检查配置后重试。|连接测试过多，请稍等一分钟再试。|在 BYOK 模式下，启用后 Issue 或 PR 的标题、正文和候选标签会发送到你的服务端点，费用由你的服务商收取。此配置仅适用于本仓库。|Jev 仅支持标签分类；OpenAI 兼容服务还可生成 AI 欢迎语。|自有服务不可用时不会回退到平台。保存服务不会自动启用意图标签或评论。|已就绪|未就绪|使用平台配置的 AI 服务。自有服务字段仅适用于 BYOK 模式。|显示密钥|隐藏密钥",
 ja: "AI サービス|本リポジトリの AI サービスを選択します。処理と許可ラベルは変更されません。|サービスモード|プラットフォームのサービス|独自プロバイダー（BYOK）|プロトコル|OpenAI 互換|Jev 分類器|ベース URL|モデル|API キー|キーは保存済みです。値は表示されません。|キーは未保存です。|空欄なら保存済みキーを維持します。URL またはプロトコルの変更には新しいキーが必要です。|サービスを保存|接続をテスト|少量の架空データで保存済み設定をテストします。先に保存してください。料金が発生する場合があります。|キーを削除|本リポジトリの保存済みキーの削除を確認します。|キーを削除しました。|AI サービスを保存しました。|接続テストに成功しました。|プロトコル、HTTPS ベース URL、モデルを確認してください。|URL またはプロトコルを変更する場合、新しい API キーを入力してください。|安全なキー保存を利用できません。管理者にお問い合わせください。|保存済みサービスへの接続または認証に失敗しました。設定を確認して再試行してください。|テストが多すぎます。1分後に再試行してください。|BYOK モードで有効にすると Issue や PR のタイトル、本文、候補ラベルを独自のエンドポイントに送信します。料金はプロバイダーから請求されます。本リポジトリのみに適用されます。|Jev はラベル分類のみ対応します。OpenAI 互換サービスは AI 挨拶文も生成できます。|BYOK が利用できなくてもプラットフォームに切り替わりません。保存してもラベルやコメントは有効になりません。|準備完了|未準備|プラットフォームの AI サービスを使用します。独自プロバイダーの項目は BYOK モード専用です。|キーを表示|キーを隠す",
 ko: "AI 서비스|이 저장소의 AI 서비스를 선택하세요. 처리 및 허용 라벨 설정은 바뀌지 않습니다.|서비스 모드|플랫폼 서비스|자체 제공업체 (BYOK)|프로토콜|OpenAI 호환|Jev 분류기|기본 URL|모델|API 키|키가 저장되어 있으며 값은 표시되지 않습니다.|저장된 키가 없습니다.|비워 두면 원래 키를 유지합니다. URL 또는 프로토콜 변경에는 새 키가 필요합니다.|서비스 저장|연결 테스트|가상 요청으로 저장된 설정을 테스트합니다. 먼저 저장하세요. 제공업체가 요금을 청구할 수 있습니다.|키 삭제|이 저장소에 저장된 키 삭제를 확인합니다.|키를 삭제했습니다.|AI 서비스를 저장했습니다.|연결 테스트에 성공했습니다.|프로토콜, HTTPS 기본 URL 및 모델을 확인하세요.|URL 또는 프로토콜 변경 시 새 API 키를 입력하세요.|보안 키 저장소를 사용할 수 없습니다. 관리자에게 문의하세요.|저장된 서비스에 연결하거나 인증할 수 없습니다. 설정을 확인하고 다시 시도하세요.|테스트가 너무 많습니다. 1분 후 다시 시도하세요.|BYOK 모드에서 활성화하면 Issue 또는 PR 제목, 본문과 후보 라벨을 자체 엔드포인트에 전송합니다. 제공업체가 비용을 청구합니다. 이 저장소에만 적용됩니다.|Jev는 라벨 분류만 지원합니다. OpenAI 호환 서비스는 AI 인사말도 생성할 수 있습니다.|BYOK 실패 시 플랫폼으로 전환하지 않습니다. 저장해도 라벨이나 댓글은 활성화되지 않습니다.|준비됨|준비 안 됨|플랫폼에 설정된 AI 서비스를 사용합니다. 자체 제공업체 필드는 BYOK 모드 전용입니다.|키 표시|키 숨기기",
 es: "Servicio de IA|Elige la IA de este repositorio. El procesamiento y las etiquetas permitidas no cambian.|Modo de servicio|Servicio de la plataforma|Proveedor propio (BYOK)|Protocolo|Compatible con OpenAI|Clasificador Jev|URL base|Modelo|Clave API|Hay una clave guardada; su valor está oculto.|No hay clave guardada.|Déjalo vacío para conservar la clave. Cambiar la URL o el protocolo requiere una clave nueva.|Guardar servicio|Probar conexión|Prueba la configuración guardada con una petición ficticia. Guarda antes. Tu proveedor puede cobrar por la prueba.|Eliminar clave|Confirmo eliminar la clave guardada de este repositorio.|Se eliminó la clave.|Servicio de IA guardado.|La conexión se probó correctamente.|Revisa el protocolo, la URL base HTTPS y el modelo.|Introduce una clave nueva al cambiar la URL o el protocolo.|El almacenamiento seguro no está disponible. Contacta al administrador.|No se pudo conectar o autenticar el servicio. Revisa su configuración e inténtalo de nuevo.|Demasiadas pruebas. Inténtalo en un minuto.|En modo BYOK, al activarlo, los títulos, contenidos y etiquetas candidatas de issues o PR se envían a tu endpoint. Tu proveedor te cobra. Solo se aplica a este repositorio.|Jev solo clasifica etiquetas. Los servicios compatibles con OpenAI también generan saludos de IA.|BYOK nunca usa la plataforma como alternativa si falla. Guardarlo no activa etiquetas ni comentarios.|Listo|No preparado|Usa el servicio de IA de la plataforma. Los campos del proveedor propio solo se aplican en BYOK.|Mostrar clave|Ocultar clave",
 pt: "Serviço de IA|Escolha a IA deste repositório. O processamento e os rótulos permitidos não mudam.|Modo de serviço|Serviço da plataforma|Seu provedor (BYOK)|Protocolo|Compatível com OpenAI|Classificador Jev|URL base|Modelo|Chave de API|Uma chave está salva; seu valor está oculto.|Nenhuma chave salva.|Deixe em branco para manter a chave. Alterar URL ou protocolo exige uma nova chave.|Salvar serviço|Testar conexão|Testa a configuração salva com uma solicitação fictícia. Salve antes. Seu provedor pode cobrar pelo teste.|Excluir chave|Confirmo a exclusão da chave salva deste repositório.|A chave foi excluída.|Serviço de IA salvo.|Teste de conexão concluído.|Confira o protocolo, a URL base HTTPS e o modelo.|Insira uma nova chave ao alterar a URL ou o protocolo.|O armazenamento seguro não está disponível. Contate o administrador.|Não foi possível conectar ou autenticar o serviço. Confira a configuração e tente novamente.|Muitos testes. Tente novamente em um minuto.|No modo BYOK, quando ativado, títulos, conteúdo e rótulos candidatos de issues ou PR são enviados ao seu endpoint. Seu provedor cobra de você. Vale apenas para este repositório.|Jev oferece apenas classificação de rótulos. Serviços compatíveis com OpenAI também geram saudações de IA.|BYOK nunca recorre à plataforma se falhar. Salvar não ativa rótulos nem comentários.|Pronto|Não pronto|Usa a IA configurada na plataforma. Campos do provedor próprio só se aplicam em BYOK.|Mostrar chave|Ocultar chave",
 id: "Layanan AI|Pilih AI repositori ini. Pengaturan pemrosesan dan label tidak berubah.|Mode layanan|Layanan platform|Penyedia sendiri (BYOK)|Protokol|Kompatibel OpenAI|Pengklasifikasi Jev|URL dasar|Model|Kunci API|Kunci tersimpan; nilainya disembunyikan.|Belum ada kunci tersimpan.|Kosongkan untuk mempertahankan kunci. Mengubah URL atau protokol memerlukan kunci baru.|Simpan layanan|Uji koneksi|Menguji konfigurasi tersimpan dengan permintaan sintetis. Simpan dahulu. Penyedia dapat mengenakan biaya.|Hapus kunci|Saya mengonfirmasi penghapusan kunci repositori ini.|Kunci telah dihapus.|Layanan AI tersimpan.|Uji koneksi berhasil.|Periksa protokol, URL dasar HTTPS, dan model.|Masukkan kunci baru saat mengubah URL atau protokol.|Penyimpanan aman tidak tersedia. Hubungi administrator.|Layanan tidak dapat dihubungi atau diautentikasi. Periksa pengaturan lalu coba lagi.|Terlalu banyak uji. Coba dalam satu menit.|Dalam mode BYOK, saat aktif, judul, isi, dan kandidat label issue atau PR dikirim ke endpoint Anda. Penyedia menagih Anda. Hanya berlaku untuk repositori ini.|Jev hanya mendukung klasifikasi label. Layanan kompatibel OpenAI juga menghasilkan sapaan AI.|BYOK yang gagal tidak beralih ke platform. Menyimpan tidak mengaktifkan label atau komentar.|Siap|Belum siap|Menggunakan AI platform. Bidang penyedia sendiri hanya berlaku dalam mode BYOK.|Tampilkan kunci|Sembunyikan kunci",
 vi: "Dịch vụ AI|Chọn AI của kho mã này. Cài đặt xử lý và nhãn không đổi.|Chế độ dịch vụ|Dịch vụ nền tảng|Nhà cung cấp riêng (BYOK)|Giao thức|Tương thích OpenAI|Bộ phân loại Jev|URL cơ sở|Mô hình|Khóa API|Đã lưu khóa; giá trị được ẩn.|Chưa lưu khóa.|Để trống để giữ khóa. Đổi URL hoặc giao thức cần khóa mới.|Lưu dịch vụ|Kiểm tra kết nối|Kiểm tra cấu hình đã lưu bằng yêu cầu giả lập. Hãy lưu trước. Nhà cung cấp có thể tính phí.|Xóa khóa|Tôi xác nhận xóa khóa của kho mã này.|Đã xóa khóa.|Đã lưu dịch vụ AI.|Kiểm tra kết nối thành công.|Kiểm tra giao thức, URL cơ sở HTTPS và mô hình.|Nhập khóa mới khi đổi URL hoặc giao thức.|Bộ lưu trữ an toàn không khả dụng. Liên hệ quản trị viên.|Không thể kết nối hoặc xác thực dịch vụ. Kiểm tra cài đặt và thử lại.|Quá nhiều lần kiểm tra. Thử lại sau một phút.|Ở chế độ BYOK, khi bật, tiêu đề, nội dung và nhãn ứng viên của issue hoặc PR được gửi đến endpoint của bạn. Nhà cung cấp tính phí cho bạn. Chỉ áp dụng cho kho mã này.|Jev chỉ phân loại nhãn. Dịch vụ tương thích OpenAI còn tạo lời chào AI.|BYOK thất bại sẽ không chuyển sang nền tảng. Lưu không bật nhãn hay bình luận.|Sẵn sàng|Chưa sẵn sàng|Dùng AI của nền tảng. Các trường nhà cung cấp riêng chỉ áp dụng ở BYOK.|Hiện khóa|Ẩn khóa",
 ar: "خدمة الذكاء الاصطناعي|اختر خدمة هذا المستودع. لا تتغير المعالجة والتسميات المسموحة.|وضع الخدمة|خدمة المنصة|مزودك الخاص (BYOK)|البروتوكول|متوافق مع OpenAI|مصنف Jev|عنوان URL الأساسي|النموذج|مفتاح API|تم حفظ مفتاح وقيمته مخفية.|لا يوجد مفتاح محفوظ.|اتركه فارغًا للاحتفاظ بالمفتاح. تغيير العنوان أو البروتوكول يتطلب مفتاحًا جديدًا.|حفظ الخدمة|اختبار الاتصال|يختبر الإعدادات المحفوظة بطلب اصطناعي صغير. احفظ أولًا. قد يفرض مزودك رسومًا.|حذف المفتاح|أؤكد حذف مفتاح هذا المستودع المحفوظ.|تم حذف المفتاح.|تم حفظ الخدمة.|نجح اختبار الاتصال.|تحقق من البروتوكول وعنوان HTTPS الأساسي والنموذج.|أدخل مفتاحًا جديدًا عند تغيير العنوان أو البروتوكول.|التخزين الآمن غير متاح. اتصل بالمسؤول.|تعذر الاتصال بالخدمة أو مصادقتها. تحقق من الإعدادات وحاول مجددًا.|اختبارات كثيرة. حاول بعد دقيقة.|في وضع BYOK، عند التفعيل تُرسل عناوين issues أو PR ومحتواها والتسميات المرشحة إلى عنوانك. يتحمل حسابك لدى المزود التكلفة. يخص هذا المستودع فقط.|يدعم Jev تصنيف التسميات فقط. تنشئ الخدمات المتوافقة مع OpenAI تحيات أيضًا.|لا ترجع BYOK إلى المنصة عند الفشل. حفظ الخدمة لا يفعّل التسميات أو التعليقات.|جاهز|غير جاهز|يستخدم خدمة المنصة. حقول المزود الخاص تخص وضع BYOK فقط.|إظهار المفتاح|إخفاء المفتاح",
};
const aiSupplement: Record<Locale,string> = {
 en: "This repository has no AI greeting service configured. Enabled comments use the plain score template.|For Jev use typesafe/jev-1.13 or a dated model such as typesafe/jev-1.13-20260917.|Saved service",
 zh: "本仓库尚未配置可生成 AI 问候的服务。启用评论后将使用固定的评分模板。|Jev 模型需为 typesafe/jev-1.13 或带日期的版本，如 typesafe/jev-1.13-20260917。|已保存的服务",
 ja: "本リポジトリに AI 挨拶サービスが設定されていません。有効なコメントには定型のスコアテンプレートを使用します。|Jev は typesafe/jev-1.13 または typesafe/jev-1.13-20260917 のような日付付きモデルを使用してください。|保存済みサービス",
 ko: "이 저장소에 AI 인사말 서비스가 설정되지 않았습니다. 활성화된 댓글은 기본 점수 템플릿을 사용합니다.|Jev는 typesafe/jev-1.13 또는 typesafe/jev-1.13-20260917 같은 날짜 버전을 사용하세요.|저장된 서비스",
 es: "Este repositorio no tiene un servicio de saludos de IA configurado. Los comentarios usan la plantilla de puntuación simple.|Para Jev usa typesafe/jev-1.13 o una versión fechada como typesafe/jev-1.13-20260917.|Servicio guardado",
 pt: "Este repositório não tem serviço de saudações de IA configurado. Os comentários usam o modelo simples de pontuação.|Para Jev use typesafe/jev-1.13 ou uma versão datada como typesafe/jev-1.13-20260917.|Serviço salvo",
 id: "Repositori ini belum memiliki layanan sapaan AI. Komentar aktif memakai templat skor biasa.|Untuk Jev gunakan typesafe/jev-1.13 atau versi bertanggal seperti typesafe/jev-1.13-20260917.|Layanan tersimpan",
 vi: "Kho mã này chưa cấu hình dịch vụ lời chào AI. Bình luận đang bật dùng mẫu điểm cơ bản.|Với Jev, dùng typesafe/jev-1.13 hoặc bản có ngày như typesafe/jev-1.13-20260917.|Dịch vụ đã lưu",
 ar: "لم يُضبط لهذا المستودع خدمة تحيات بالذكاء الاصطناعي. تستخدم التعليقات المفعلة قالب الدرجة البسيط.|استخدم مع Jev النموذج typesafe/jev-1.13 أو إصدارًا مؤرخًا مثل typesafe/jev-1.13-20260917.|الخدمة المحفوظة",
};
export const ADMIN_MESSAGES = Object.fromEntries(Object.entries(catalogs).map(([locale, text]) => {
  const values = (text + "|" + interactionCatalogs[locale as Locale] + "|" + globalCatalogs[locale as Locale] + "|" + aiCatalogs[locale as Locale] + "|" + aiSupplement[locale as Locale]).split("|");
  if (values.length !== keys.length) throw new Error(`Incomplete admin catalog: ${locale}`);
  return [locale, Object.fromEntries(keys.map((key, i) => [key, values[i]]))];
})) as Record<Locale,AdminMessages>;

/** Known service actions never expose implementation names or stored details. */
export function aiAuditLabel(locale: Locale, action: string): string | undefined {
  const d = ADMIN_MESSAGES[locale];
  if (action === "ai_provider.update") return d.aiSaved;
  if (action === "ai_provider.key_remove") return d.aiRemoved;
  if (action === "ai_provider.test") return d.aiTested;
  return undefined;
}
