import { format, type Locale, type Messages } from "./i18n";
import { ADMIN_MESSAGES, type AdminMessages } from "./admin-i18n";
import type { AdminGlobalData } from "./admin-global-data";
import { JOB_KINDS, JOB_STATES, type AdminData, type AdminTask, type AdminAudit } from "./admin-data";

export const escapeHtml = (value: unknown) => String(value).replace(/[&<>"']/g, x => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[x]!);
const e = escapeHtml;
const rowContext = (context:AdminContext, installation?:number):AdminContext => installation ? {...context,installation:String(installation),global:false} : context;
export type AdminGlobalView = AdminGlobalData;
export interface AdminContext {
  path: string;
  global?: boolean;
  installation?: string;
  account?: string;
  installations?: { id: number; account: string }[];
  locale: Locale;
  lang?: string;
  repoPage?: number;
  repositoryQuery?: { q?: string; processing?: string };
}
const paths = { overview: "/admin", repositories: "/admin/repositories", tasks: "/admin/tasks", activity: "/admin/activity", installations: "/admin/installations" } as const;
const svg = (body: string) => `<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${body}</svg>`;
const icons = {
 overview: svg('<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>'),
 repositories: svg('<path d="M4 19V5a2 2 0 0 1 2-2h13v18H6a2 2 0 0 1 0-4h13M8 7h6"/>'),
 tasks: svg('<rect x="4" y="3" width="16" height="18" rx="2"/><path d="m8 8 1 1 2-2M14 8h3m-9 6 1 1 2-2M14 14h3"/>'),
 activity: svg('<path d="M3 12h4l3-8 4 16 3-8h4"/>'),
 installations: svg('<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 9h18M8 4v16"/>'),
 menu: svg('<path d="M4 6h16M4 12h16M4 18h16"/>'),
 close: svg('<path d="m6 6 12 12M18 6 6 18"/>'),
 arrow: svg('<path d="M5 12h14m-5-5 5 5-5 5"/>'),
};
export function adminLink(context: AdminContext, path: string, extra: Record<string,string|number|undefined> = {}) {
  const params = new URLSearchParams();
  if (context.installation) params.set("installation_id", context.installation);
  if (context.lang) params.set("lang", context.lang);
  if (context.repoPage && context.repoPage > 1 && path !== paths.installations) params.set("repo_page",String(context.repoPage));
  if (context.repositoryQuery && path === paths.repositories) {
    if (context.repositoryQuery.q) params.set("q",context.repositoryQuery.q);
    if (context.repositoryQuery.processing) params.set("processing",context.repositoryQuery.processing);
  }
  if (context.repositoryQuery && (path === "/admin/repo" || path === "/admin/intent-preview" || path === "/admin/toggle")) {
    if (context.repositoryQuery.q) params.set("return_q",context.repositoryQuery.q);
    if (context.repositoryQuery.processing) params.set("return_processing",context.repositoryQuery.processing);
  }
  for (const [key,value] of Object.entries(extra)) if(value !== undefined && value !== "") params.set(key,String(value));
  return path + (params.size ? `?${params}` : "");
}
export function adminShell(context: AdminContext, t: Messages, content: string, controls: string, session?: string) {
  const d = ADMIN_MESSAGES[context.locale];
  const active = context.path === "/admin" ? "overview" : context.path === "/admin/repo" || context.path === "/admin/intent-preview" ? "repositories" : context.path === "/admin/installations" || !context.installation ? "installations" : Object.entries(paths).find(([,path])=>path===context.path)?.[0] ?? "overview";
  const nav = (Object.keys(paths) as (keyof typeof paths)[]).map(key => `<a class="side-link" href="${e(adminLink(key==="overview"?{...context,installation:undefined,repoPage:undefined,repositoryQuery:undefined,global:true}:context,paths[key]))}"${active===key?' aria-current="page"':""}>${icons[key]}<span>${e(d[key])}</span></a>`).join("");
  const installs = context.installations ?? (context.installation ? [{ id: Number(context.installation),account: context.account || `#${context.installation}` }] : []);
  const current = installs.find(x => String(x.id) === context.installation);
  const accountName = context.global ? d.allAccounts : current?.account || context.account || d.installations;
  const accountBadge = `<span class="context-badge" aria-hidden="true">${e(accountName.slice(0,2).toUpperCase())}</span>`;
  const switchPath = context.path === "/admin/repo" || context.path === "/admin/intent-preview" ? paths.repositories : Object.values(paths).includes(context.path as typeof paths[keyof typeof paths]) ? context.path : paths.overview;
  const accountPicker = !installs.length ? `<span class="account-name">${e(context.installations !== undefined ? (context.global ? d.allAccounts : d.installations) : "ghfind Review")}</span>` : (installs.length > 1 || context.global) ? `<details class="account-picker" data-account-picker><summary aria-label="${e(d.switchAccount)}" aria-expanded="false">${accountBadge}<span class="account-name"><bdi>${e(accountName)}</bdi></span><span class="account-chevron" aria-hidden="true">⌄</span></summary><div class="account-popover"><p>${e(d.accountScope)}</p><nav aria-label="${e(d.switchAccount)}"><a href="${e(adminLink({...context,installation:undefined,repoPage:undefined,repositoryQuery:undefined},paths.overview))}"${context.global?' aria-current="true"':""}><span>${e(d.allAccounts)}</span>${context.global?`<span class="account-current">${e(d.currentAccount)}</span>`:""}</a>${installs.map(x=>`<a href="${e(adminLink({...context, installation:String(x.id), repoPage:undefined, repositoryQuery:undefined},switchPath))}"${!context.global&&String(x.id)===context.installation?' aria-current="true"':""}><span class="context-badge" aria-hidden="true">${e(x.account.slice(0,2).toUpperCase())}</span><span><bdi>${e(x.account)}</bdi><small dir="ltr">#${x.id}</small></span>${!context.global&&String(x.id)===context.installation?`<span class="account-current">${e(d.currentAccount)}</span>`:""}</a>`).join("")}</nav><a class="account-manage" href="${e(adminLink(context,paths.installations))}">${e(d.manageInstallations)}</a></div></details>` : `<div class="account-static">${accountBadge}<span class="account-name"><bdi>${e(accountName)}</bdi></span></div><a class="context-manage" href="${e(adminLink(context,paths.installations))}">${e(d.manageInstallations)}</a>`;
  return `<noscript><style>@media(max-width:720px){.admin-app .sidebar{position:static;width:100%;max-width:none;height:auto;visibility:visible;transform:none!important;border-inline-end:0;border-bottom:1px solid var(--border);gap:12px;padding:16px}.admin-app .side-nav{grid-template-columns:repeat(2,minmax(0,1fr))}.admin-app .side-bottom{margin-top:0}.admin-app .mobile-menu,.admin-app .sidebar-close{display:none}}</style></noscript><div class="admin-app" data-submitting="${e(d.submitting)}" data-submit-hint="${e(d.submittedHint)}" data-unsaved-message="${e(d.unsavedChanges)}"><div class="sidebar-overlay" aria-hidden="true"></div><aside class="sidebar" id="admin-sidebar" aria-label="${e(d.navigation)}"><a class="brand" href="/"><img src="/avatar.png" width="30" height="30" alt=""><span class="brand-copy">ghfind<small>REVIEW BOT</small></span></a><button class="sidebar-close" type="button" data-menu-close aria-label="${e(d.closeMenu)}">${icons.close}</button><div><p class="side-caption">${e(d.workspace)}</p><nav class="side-nav">${nav}</nav></div><div class="side-bottom"><a href="https://github.com/settings/installations">${e(t.admin.manageAccess)}&nbsp;↗</a><a href="https://github.com/hikariming/ghfind">${e(t.footer.source)}&nbsp;↗</a>${session?`<form method="post" action="/logout"><input type="hidden" name="csrf" value="${e(session)}"><button class="session-signout">${e(t.admin.signOut)}</button></form>`:""}<div class="side-meta">ghfind Review · GitHub App</div></div></aside><div class="admin-workspace"><header class="admin-top"><div class="context"><button class="mobile-menu" type="button" data-menu-button aria-controls="admin-sidebar" aria-expanded="false" aria-label="${e(d.openMenu)}">${icons.menu}</button>${accountPicker}</div><div class="tools">${controls}</div></header><main class="admin-main" id="main-content">${content}</main><div class="admin-foot"><span>© ghfind</span><a href="/notifications">${e(t.footer.emails)}</a><a href="/privacy">${e(t.footer.privacy)}</a><a href="https://ghfind.com${context.locale==="zh"?"":`/${context.locale}`}/github-bot">ghfind.com ↗</a></div></div></div>`;
}
export const pageHead = (title: string, lead: string, actions="") => `<div class="page-head"><div><h1>${e(title)}</h1><p>${e(lead)}</p></div>${actions?`<div class="actions">${actions}</div>`:""}</div>`;
const button = (label:string,url:string,primary=false) => `<a class="btn${primary?" primary":""}" href="${e(url)}">${e(label)}</a>`;
const sectionHead = (title:string,sub="",link="",label="") => `<div class="section-head"><div><h2>${e(title)}</h2>${sub?`<p>${e(sub)}</p>`:""}</div>${link?`<a class="textlink" href="${e(link)}">${e(label)} →</a>`:""}</div>`;
const date = (value:number) => `<time dir="ltr" datetime="${new Date(value).toISOString()}">${new Date(value).toISOString().slice(0,16).replace("T"," ")} UTC</time>`;
export function scopeNote(data:AdminData,d:AdminMessages) {
  return `<div class="scope-note"><span class="scope-label">${e(d.scoped)}</span><span>${e(format(d.scope,{authorized:String(data.scope.authorized),checked:String(data.scope.checked),total:String(data.scope.totalAccessible)}))}</span>${data.scope.partial?`<span>${e(d.partial)}</span>`:""}</div>`;
}
const feature = (on:boolean,d:AdminMessages) => `<span class="feature-status"><span class="status-dot${on?" on":""}" aria-hidden="true"></span>${e(on?d.on:d.off)}</span>`;
export function installationPage(c:AdminContext,t:Messages,installUrl?:string) {
 const d=ADMIN_MESSAGES[c.locale];
 const rows=(c.installations??[]).map(x=>{const current=!c.global&&String(x.id)===c.installation,target={...c,installation:String(x.id),global:false,repoPage:undefined,repositoryQuery:undefined};return `<tr${current?' data-current="true"':""}><td><div class="account-cell"><span class="context-badge" aria-hidden="true">${e(x.account.slice(0,2).toUpperCase())}</span><div><a class="repo-name" href="${e(adminLink(target,paths.overview))}"><bdi>${e(x.account)}</bdi></a>${current?`<span class="current-note">${e(d.currentAccount)}</span>`:""}</div></div></td><td><span class="repo-meta" dir="ltr">#${x.id}</span></td><td><div class="actions">${button(d.overview,adminLink(target,paths.overview))}${button(d.repositories,adminLink(target,paths.repositories))}</div></td><td><a class="installation-access textlink" href="https://github.com/settings/installations/${x.id}">${e(t.admin.manageAccess)} ↗</a></td></tr>`}).join("");
 return pageHead(d.installations,t.admin.installationsBody,installUrl?button(t.home.install,installUrl):"")+(rows?`<section class="work-section installation-directory"><div class="table"><table><thead><tr><th>${e(d.accounts)}</th><th>GitHub App</th><th>${e(t.setup.action)}</th><th>${e(t.admin.manageAccess)}</th></tr></thead><tbody>${rows}</tbody></table></div></section>`:`<div class="admin-empty"><h2>${e(t.admin.noInstallations)}</h2><p>${e(t.admin.installationsBody)}</p>${installUrl?`<div class="actions">${button(t.home.install,installUrl,true)}</div>`:`<p class="result">${e(t.home.notOpen)}</p>`}</div>`);
}

function emptyRepositories(t:Messages) {
  return `<div class="admin-empty"><div class="empty-icon">${icons.repositories}</div><h2>${e(t.admin.noRepositories)}</h2><p>${e(t.admin.noRepositoriesHint)}</p><div class="actions">${button(t.admin.manageAccess,"https://github.com/settings/installations")}</div></div>`;
}
export function repoPagination(c:AdminContext,data:AdminData,extra:Record<string,string|number|undefined>={}) {
  const d=ADMIN_MESSAGES[c.locale];
  if(!data.scope.hasNext&&!data.scope.hasPrevious)return "";
  return `<div class="pagination" data-repo-pagination><span>${e(d.nextRepoPage)} · ${e(d.page)} ${data.scope.page}</span><div class="actions">${data.scope.hasPrevious?button(d.previous,adminLink(c,c.path,{...extra,repo_page:data.scope.page-1,task_page:undefined,activity_page:undefined})):""}${data.scope.hasNext?button(d.next,adminLink(c,c.path,{...extra,repo_page:data.scope.page+1})):""}</div></div>`;
}
function historyPagination(c:AdminContext,url:URL,current:number,previous:boolean,next:boolean,key:string,truncated=false){
  const d=ADMIN_MESSAGES[c.locale];
  const link=(n:number)=>{const copy=new URL(url);copy.searchParams.set(key,String(n));return copy.pathname+copy.search};
  return `<div class="pagination"><span>${e(d.page)} ${current}${truncated?` · ${e(d.historyLimit)}`:""}</span><div class="actions">${previous?button(d.previous,link(current-1)):""}${next?button(d.next,link(current+1)):""}</div></div>`;
}
export function taskTable(c:AdminContext,t:Messages,rows:AdminTask[],csrf:string,compact=false,taskQuery:Record<string,string|number|undefined>={}){
  const d=ADMIN_MESSAGES[c.locale];
  if(!rows.length)return `<div class="admin-empty"><p>${e(t.setup.empty)}</p></div>`;
  return `<div class="table"><table><thead><tr><th>${e(t.setup.repository)}</th><th>${e(t.setup.task)}</th><th>${e(t.setup.status)}</th>${compact?"":`<th>${e(d.updated)}</th>`}<th>${e(t.setup.action)}</th></tr></thead><tbody>${rows.map(job=>`<tr><td><a class="repo-name" href="${e(adminLink(rowContext(c,job.installation),"/admin/repo",{repository:job.repository}))}"><bdi>${e(job.fullName)}</bdi></a><span class="repo-meta" dir="ltr">${e(job.id.slice(0,48))}</span></td><td>${e(t.setup.kinds[job.kind])}${job.pr?` <a class="textlink" href="https://github.com/${e(job.fullName)}/issues/${job.pr}">#${job.pr}</a>`:""}</td><td><span class="state-text" data-state="${e(job.state)}">${e(t.setup.states[job.state as keyof typeof t.setup.states]??job.state)}</span>${job.result?`<span class="result task-result">${e(job.result.slice(0,500))}</span>`:""}</td>${compact?"":`<td><span class="repo-meta">${date(job.updated)}</span></td>`}<td>${job.state==="failed"&&job.admin?`<form method="post" action="${e(adminLink(rowContext(c,job.installation),"/retry",taskQuery))}"><input type="hidden" name="csrf" value="${e(csrf)}"><input type="hidden" name="id" value="${e(job.id)}"><input type="hidden" name="return_to" value="tasks"><button class="btn">${e(t.setup.retry)}</button></form>`:button(compact?d.settings:d.openSettings,adminLink(rowContext(c,job.installation),"/admin/repo",{repository:job.repository}))}</td></tr>`).join("")}</tbody></table></div>`;
}
const kpiStrip = (items:{label:string;value:number;hint:string}[]) => `<div class="kpi-strip">${items.map(m=>`<div class="kpi"><span class="kpi-label">${e(m.label)}</span><strong class="kpi-value">${m.value}</strong><span class="kpi-hint">${e(m.hint)}</span></div>`).join("")}</div>`;
function repositoryLines(c:AdminContext,t:Messages,data:AdminData){
 const d=ADMIN_MESSAGES[c.locale];
 return `<ul class="repository-lines">${data.repositories.slice(0,8).map(r=>{const target=rowContext(c,(r as typeof r & {installation?:number}).installation);return `<li><a href="${e(adminLink(target,"/admin/repo",{repository:r.id}))}"><strong><bdi>${e(r.fullName)}</bdi></strong><span class="status-text">${e(r.settings.issuesEnabled||r.settings.prsEnabled?d.active:d.paused)}</span></a><span class="repo-meta">${e(r.admin?d.admin:d.readOnly)} · ${e(t.admin.comments)} ${e(r.settings.commentsEnabled?d.on:d.off)} · ${e(t.admin.triage)} ${e(r.settings.triageEnabled?d.on:d.off)}</span></li>`}).join("")}</ul>`;
}
export function dashboardPage(c:AdminContext,t:Messages,data:AdminData,csrf:string){
 const d=ADMIN_MESSAGES[c.locale],o=data.overview;
 return pageHead(d.overview,d.overviewLead,button(d.repositories,adminLink(c,paths.repositories)))+scopeNote(data,d)+(data.repositories.length?kpiStrip([{label:d.visibleRepositories,value:data.scope.authorized,hint:d.scoped},{label:d.jobs,value:o.totalJobs,hint:d.window},{label:d.workQueue,value:o.jobStates.pending+o.jobStates.running,hint:`${d.pending}: ${o.jobStates.pending} · ${d.running}: ${o.jobStates.running}`},{label:d.failed,value:o.jobStates.failed,hint:`${d.due}: ${o.duePending} · ${d.stale}: ${o.staleRunning}`}])+`<section class="work-section">${sectionHead(d.recentTasks,d.allRetained,adminLink(c,paths.tasks),d.viewAll)}${taskTable(c,t,data.tasks.rows.slice(0,8),csrf)}</section><div class="workspace-split"><section class="work-section">${sectionHead(d.repositoryStatus,"",adminLink(c,paths.repositories),d.viewAll)}${repositoryLines(c,t,data)}</section><section class="work-section">${sectionHead(d.activity,"",adminLink(c,paths.activity),d.viewAll)}${auditList(c,t,data.activity.rows.slice(0,5),true)}</section></div>`:emptyRepositories(t))+repoPagination(c,data);
}
export function globalDashboardPage(c:AdminContext,t:Messages,data:AdminGlobalView,csrf:string,installUrl?:string){
 const d=ADMIN_MESSAGES[c.locale],o=data.overview,g=data.globalScope,global={...c,global:true,installation:undefined,repoPage:undefined,repositoryQuery:undefined};
 if(g.totalInstallations===0)return pageHead(d.overview,d.globalLead)+`<div class="admin-empty"><h2>${e(t.admin.noInstallations)}</h2><p>${e(t.admin.installationsBody)}</p><div class="actions">${button(installUrl?t.home.install:d.manageInstallations,installUrl||"https://github.com/settings/installations",true)}</div></div>`;
 const coverage=`<div class="scope-note"><span class="scope-label">${e(d.allAccounts)}</span><span>${e(format(d.globalCoverage,{checked:String(g.checkedInstallations),total:String(g.totalInstallations),authorized:String(data.scope.authorized),checkedRepos:String(data.scope.checked)}))}</span>${g.partial?`<span>${e(d.globalPartial)}</span>`:""}</div>`;
 const accounts=`<section class="work-section">${sectionHead(d.accounts,`${d.accountsLead} ${d.window}.`,adminLink(global,paths.installations),d.manageInstallations)}<div class="table"><table><thead><tr><th>${e(d.accounts)}</th><th>${e(d.writableRepositories)}</th><th>${e(t.admin.processing)}</th><th>${e(t.admin.triage)}</th><th>${e(d.workQueue)}</th><th>${e(d.failed)}</th><th>${e(t.setup.action)}</th></tr></thead><tbody>${data.accounts.map(a=>{const target={...c,global:false,installation:String(a.id),repoPage:undefined,repositoryQuery:undefined};return `<tr><td><a class="repo-name" href="${e(adminLink(target,paths.overview))}"><bdi>${e(a.account)}</bdi></a><span class="repo-meta" dir="ltr">#${a.id}</span>${a.partial?`<span class="repo-meta">${e(d.coverageLimited)}</span>`:""}</td><td>${a.writable}<span class="repo-meta">${a.checked} / ${a.accessible}</span></td><td><a class="textlink" href="${e(adminLink(target,paths.repositories,{processing:"active"}))}">${a.processing}</a><span class="repo-meta">${e(d.paused)}: ${a.paused}</span></td><td>${a.triage}</td><td><a class="textlink" href="${e(adminLink(target,paths.tasks))}">${a.pending+a.running}</a><span class="repo-meta">${e(d.running)}: ${a.running}</span></td><td><a class="textlink state-text" href="${e(adminLink(target,paths.tasks,{status:"failed"}))}"${a.failed?' data-state="failed"':""}>${a.failed}</a></td><td>${button(d.repositories,adminLink(target,paths.repositories))}</td></tr>`}).join("")}</tbody></table></div></section>`;
 const accountPaging=g.hasPrevious||g.hasNext?`<div class="pagination"><span>${e(d.accountPage)} ${g.installationPage}</span><div class="actions">${g.hasPrevious?button(d.previous,adminLink(global,paths.overview,{account_page:g.installationPage-1,repo_page:data.scope.page})):""}${g.hasNext?button(d.next,adminLink(global,paths.overview,{account_page:g.installationPage+1,repo_page:data.scope.page})):""}</div></div>`:"";
 return pageHead(d.overview,d.globalLead,button(d.manageInstallations,adminLink(global,paths.installations)))+coverage+kpiStrip([{label:d.visibleRepositories,value:data.scope.authorized,hint:d.scoped},{label:d.jobs,value:o.totalJobs,hint:d.window},{label:d.workQueue,value:o.jobStates.pending+o.jobStates.running,hint:`${d.pending}: ${o.jobStates.pending} · ${d.running}: ${o.jobStates.running}`},{label:d.failed,value:o.jobStates.failed,hint:`${d.due}: ${o.duePending} · ${d.stale}: ${o.staleRunning}`}])+accounts+accountPaging+`<section class="work-section">${sectionHead(d.recentTasks,d.allRetained)}${taskTable(c,t,data.tasks.rows.slice(0,10),csrf)}</section><section class="work-section">${sectionHead(d.activity,d.allRetained)}${auditList(c,t,data.activity.rows.slice(0,8))}</section>`+repoPagination(global,data,{account_page:g.installationPage});
}

export function repositoriesPage(c:AdminContext,t:Messages,data:AdminData,csrf:string,url:URL){
 const d=ADMIN_MESSAGES[c.locale],q=(url.searchParams.get("q")??"").trim(),processing=url.searchParams.get("processing")??"";
 c={...c,repositoryQuery:{q,processing}};
 const rows=data.repositories.map(r=>{const active=r.settings.issuesEnabled||r.settings.prsEnabled,visible=(!q||r.fullName.toLowerCase().includes(q.toLowerCase()))&&(!processing||(active?"active":"paused")===processing);return `<tr data-repo-row data-repo-name="${e(r.fullName)}" data-processing="${active?"active":"paused"}"${visible?"":" hidden"}><td><a class="repo-name" data-repo-settings href="${e(adminLink(c,"/admin/repo",{repository:r.id}))}"><bdi>${e(r.fullName)}</bdi></a><span class="repo-meta">${e(r.admin?d.admin:d.readOnly)}</span></td><td>${r.admin?`<form method="post" data-repo-toggle action="${e(adminLink(c,"/admin/toggle",{repository:r.id,return_q:q,return_processing:processing}))}"><input type="hidden" name="csrf" value="${e(csrf)}"><button class="processing-switch" role="switch" aria-checked="${active}" aria-label="${e(t.admin.processing)} · ${e(r.fullName)}" name="enabled" value="${active?"off":"on"}"><span aria-hidden="true"></span><b>${e(active?d.active:d.paused)}</b></button></form>`:`<span class="feature-status"><span class="status-dot${active?" on":""}"></span>${e(active?d.active:d.paused)}</span>`}</td><td>${feature(r.settings.commentsEnabled,d)}</td><td>${feature(r.settings.triageEnabled,d)}</td><td><span class="repo-meta">${r.lastActivity?date(r.lastActivity):e(d.noActivity)}</span></td><td><a class="btn" data-repo-settings href="${e(adminLink(c,"/admin/repo",{repository:r.id}))}">${e(d.openSettings)}</a></td></tr>`}).join("");
 const shown=data.repositories.some(r=>(!q||r.fullName.toLowerCase().includes(q.toLowerCase()))&&(!processing||(r.settings.issuesEnabled||r.settings.prsEnabled?"active":"paused")===processing));
 return pageHead(d.repositories,d.repositoriesLead,button(t.admin.manageAccess,"https://github.com/settings/installations"))+scopeNote(data,d)+(data.repositories.length?`<form class="filter-bar" method="get" data-local-filter><input type="hidden" name="installation_id" value="${e(c.installation)}">${c.lang?`<input type="hidden" name="lang" value="${e(c.lang)}">`:""}${c.repoPage&&c.repoPage>1?`<input type="hidden" name="repo_page" value="${c.repoPage}">`:""}<label class="field search-field"><span>${e(d.search)}</span><input type="search" name="q" maxlength="100" value="${e(q)}" placeholder="owner/repository"><button type="button" class="clear-search" data-search-clear${q?"":" hidden"}>${e(d.clearSearch)}</button></label><label class="field"><span>${e(t.admin.processing)}</span><select name="processing"><option value="">${e(d.all)}</option><option value="active"${processing==="active"?" selected":""}>${e(d.active)}</option><option value="paused"${processing==="paused"?" selected":""}>${e(d.paused)}</option></select></label><button class="btn">${e(d.filter)}</button></form><div class="work-section"><div class="table"><table><thead><tr><th>${e(t.setup.repository)}</th><th>${e(t.admin.processing)}</th><th>${e(t.admin.comments)}</th><th>${e(t.admin.triage)}</th><th>${e(d.updated)}</th><th>${e(t.setup.action)}</th></tr></thead><tbody>${rows}</tbody></table></div><p class="empty" data-filter-empty${shown?" hidden":""}>${e(d.noResults)}</p></div><p class="fine">${e(d.processingHint)}</p>`:emptyRepositories(t))+repoPagination(c,data,{q,processing});
}
export function tasksPage(c:AdminContext,t:Messages,data:AdminData,csrf:string,url:URL){
 const d=ADMIN_MESSAGES[c.locale],f=data.tasks.filters;
 const select=(name:string,label:string,values:{value:string;label:string}[],selected="")=>`<label class="field"><span>${e(label)}</span><select name="${name}"><option value="">${e(d.all)}</option>${values.map(x=>`<option value="${e(x.value)}"${x.value===selected?" selected":""}>${e(x.label)}</option>`).join("")}</select></label>`;
 return pageHead(d.tasks,d.tasksLead,button(t.admin.cleanRefresh,url.pathname+url.search))+scopeNote(data,d)+`<form method="get" class="filter-bar"><input type="hidden" name="installation_id" value="${e(c.installation)}">${c.lang?`<input type="hidden" name="lang" value="${e(c.lang)}">`:""}<input type="hidden" name="repo_page" value="${data.scope.page}"><label class="field search-field"><span>${e(d.search)}</span><input type="search" name="q" maxlength="100" value="${e(f.q)}"></label>${select("repository",t.setup.repository,data.repositories.map(r=>({value:String(r.id),label:r.fullName})),f.repository?String(f.repository):"")}${select("status",t.setup.status,JOB_STATES.map(s=>({value:s,label:t.setup.states[s as keyof typeof t.setup.states]??s})),f.status)}${select("kind",t.setup.task,JOB_KINDS.map(k=>({value:k,label:t.setup.kinds[k]})),f.kind)}<button class="btn primary">${e(d.filter)}</button></form><section class="work-section">${sectionHead(d.jobs,d.allRetained)}${taskTable(c,t,data.tasks.rows,csrf,false,{q:f.q,repository:f.repository,status:f.status,kind:f.kind,task_page:data.tasks.page})}</section>${historyPagination(c,url,data.tasks.page,data.tasks.hasPrevious,data.tasks.hasNext,"task_page",data.tasks.truncated)}<section class="cleanup-summary">${sectionHead(d.cleanupTasks,d.allRetained)}<div class="work-section">${data.cleanups.length?`<div class="table"><table><thead><tr><th>${e(t.setup.repository)}</th><th>${e(t.setup.status)}</th><th>${e(d.updated)}</th><th>${e(t.setup.action)}</th></tr></thead><tbody>${data.cleanups.map(x=>`<tr><td><a class="repo-name" href="${e(adminLink(c,"/admin/repo",{repository:x.repository,tab:"cleanup"}))}"><bdi>${e(x.fullName)}</bdi></a><span class="repo-meta" dir="ltr">#${e(x.id.slice(0,8))}</span></td><td><span class="state-text" data-state="${e(x.state)}">${e(t.admin.cleanStates[x.state])}</span><span class="result">${e(format(d.scanned,{done:String(x.done),skipped:String(x.skipped),total:String(x.total)}))}</span></td><td><span class="repo-meta">${date(x.updated)}</span></td><td>${button(t.admin.cleanup,adminLink(c,"/admin/repo",{repository:x.repository,tab:"cleanup"}))}</td></tr>`).join("")}</tbody></table></div>`:`<p class="empty">${e(t.admin.cleanNever)}</p>`}</div>${data.cleanupsHasMore?`<p class="fine">${e(d.cleanupLimit)}</p>`:""}</section>`+repoPagination(c,data);
}
function detail(t:Messages,x:AdminAudit){
 const d=(x.detail&&typeof x.detail==="object"?x.detail:{}) as Record<string,unknown>,a=t.admin;
 const n=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)?String(v):null;
 if(x.action==="backfill"&&n(d.limit))return format(a.activityLimit,{count:n(d.limit)!});
 if(x.action==="retry"&&n(d.retried))return format(a.activityRetried,{count:n(d.retried)!});
 if(x.action==="pause"&&n(d.cancelled_jobs??d.cancelled))return format(a.activityCancelled,{count:n(d.cancelled_jobs??d.cancelled)!});
 if(x.action==="settings.update"&&Array.isArray(d.changed)&&d.changed.length)return format(a.activityChanged,{fields:d.changed.slice(0,6).map(k=>String(k).slice(0,40)).join(", ")});
 return x.action.startsWith("cleanup.")&&typeof d.id==="string"?`#${d.id.slice(0,8)}`:"";
}
export function auditList(c:AdminContext,t:Messages,rows:AdminAudit[],compact=false){
 if(!rows.length)return `<p class="result">${e(t.admin.activityEmpty)}</p>`;
 return `<div class="table audit-table"><table><thead><tr><th>${e(ADMIN_MESSAGES[c.locale].activity)}</th><th>${e(t.setup.repository)}</th>${compact?"":`<th>${e(ADMIN_MESSAGES[c.locale].updated)}</th>`}</tr></thead><tbody>${rows.map(x=>`<tr><td><span class="audit-action">${e(t.admin.activityActions[x.action as keyof typeof t.admin.activityActions]??x.action)}</span>${detail(t,x)?`<span class="audit-detail"><bdi>${e(detail(t,x))}</bdi></span>`:""}<span class="repo-meta"><bdi>${e(x.actor)}</bdi> · ${e(t.admin.activityVia[x.via])}${compact?`<br>${date(x.created)}`:""}</span></td><td><a class="repo-name" href="${e(adminLink(rowContext(c,(x as AdminAudit & {installation?:number}).installation),"/admin/repo",{repository:x.repository,tab:"activity"}))}"><bdi>${e(x.fullName)}</bdi></a></td>${compact?"":`<td>${date(x.created)}</td>`}</tr>`).join("")}</tbody></table></div>`;
}

export function activityPage(c:AdminContext,t:Messages,data:AdminData,url:URL){
 const d=ADMIN_MESSAGES[c.locale];
 return pageHead(d.activity,d.activityLead,button(t.admin.cleanRefresh,url.pathname+url.search))+scopeNote(data,d)+`<section class="work-section">${sectionHead(d.activity,d.allRetained)}${auditList(c,t,data.activity.rows)}</section>${historyPagination(c,url,data.activity.page,data.activity.hasPrevious,data.activity.hasNext,"activity_page",data.activity.truncated)}`+repoPagination(c,data);
}
